
local e=expect_type(KEYS[1],"string","placement") or expect_type(KEYS[2],"set","nodes") or expect_type(KEYS[3],"set","invalid") or expect_type(KEYS[4],"string","round_robin") or expect_type(KEYS[5],"zset","leases") or expect_type(KEYS[6],"string","sequence") or expect_type(KEYS[7],"stream","events") or expect_type(KEYS[8],"zset","old_index") or expect_type(KEYS[9],"string","old_node") or expect_type(KEYS[10],"zset","owner_leases");if e then return e end
local existing_raw=redis.call("GET",KEYS[1]);local existing,xe=decode(existing_raw,"placement");if xe then return xe end;local now=now_millis()
if existing_raw then if existing_raw~=ARGV[4] then return "conflict" end;if existing["GrainKey"]~=ARGV[3] then return redis.error_reply("IDENTITY_MISMATCH") end;if existing["Status"]=="active" then local nr=redis.call("GET",KEYS[9]);local oldnode;oldnode,xe=decode(nr,"owner_node");if xe then return xe end;local score=oldnode and redis.call("ZSCORE",KEYS[10],KEYS[9]) or nil;if oldnode and oldnode["NodeKey"]==KEYS[9] and existing["NodeIdentity"]==oldnode["NodeIdentity"] and existing["OwnerNodeSessionID"]==oldnode["NodeSessionID"] and (oldnode["Status"]=="active" or oldnode["Status"]=="draining") and score and tonumber(score)==tonumber(oldnode["Lease"]["ExpireAtUnixMilli"] or -1) and tonumber(score)>now then return existing_raw end;return "owner_unavailable" end end
local node_keys=redis.call("SMEMBERS",KEYS[2]);table.sort(node_keys);local candidates={}
for _,key in ipairs(node_keys) do local te=expect_type(key,"string","candidate_node");if te then return te end;local nr=redis.call("GET",key);local n,ne=decode(nr,"candidate_node");if ne then return ne end;if n then local index_error=expect_type(n["PlacementNodeKey"],"zset","candidate_index");if index_error then return index_error end;local score=redis.call("ZSCORE",KEYS[5],key);if n["NodeKey"]==key and n["NodeType"]==ARGV[6] and n["NodeGroup"]==ARGV[7] and n["Status"]=="active" and redis.call("SISMEMBER",KEYS[3],n["NodeName"])==0 and score and tonumber(score)==tonumber(n["Lease"]["ExpireAtUnixMilli"] or -1) and tonumber(score)>now then table.insert(candidates,{key=key,node=n}) end end end
if #candidates==0 then return "no_available_node" end
local rr,re=read_counter(KEYS[4],"round_robin","9223372036854775807");if re then return re end;local seq,se=read_counter(KEYS[6],"sequence","9007199254740991");if se then return se end
local chosen=choose_candidate(candidates,rr,ARGV[8],now,tonumber(ARGV[9]),tonumber(ARGV[10]),tonumber(ARGV[11]),tonumber(ARGV[12]));if not chosen then return "no_available_node" end;local version=1;local p={GrainID=ARGV[1],Kind=ARGV[2],GrainKey=ARGV[3],PlacementID=ARGV[13],NodeIdentity=chosen.node["NodeIdentity"],OwnerNodeSessionID=chosen.node["NodeSessionID"],Version=version,Status="active",CreateTimeUnixMilli=now,UpdateTimeUnixMilli=now};local encoded=cjson.encode(p)
redis.call("INCR",KEYS[4]);local nextseq=redis.call("INCR",KEYS[6]);if existing then redis.call("ZREM",KEYS[8],ARGV[3]) end;redis.call("SET",KEYS[1],encoded);redis.call("ZADD",chosen.node["PlacementNodeKey"],nextseq,ARGV[3]);event(KEYS[7],ARGV[5],ARGV[3],p["PlacementID"],chosen.node["NodeIdentity"],chosen.node["NodeSessionID"],tostring(version),"0");return encoded

