
local e=expect_type(KEYS[1],"string","placement") or expect_type(KEYS[2],"string","owner_node") or expect_type(KEYS[3],"string","target_node") or expect_type(KEYS[4],"zset","old_index") or expect_type(KEYS[5],"zset","new_index") or expect_type(KEYS[6],"zset","target_leases") or expect_type(KEYS[7],"stream","events") or expect_type(KEYS[8],"zset","owner_leases") or expect_type(KEYS[9],"set","target_invalid") or expect_type(KEYS[10],"string","sequence");if e then return e end
local raw=redis.call("GET",KEYS[1]);if not raw then return "placement_not_found" end;if raw~=ARGV[2] then return "version_conflict" end;local p,pe=decode(raw,"placement");if pe then return pe end
local ownerraw=redis.call("GET",KEYS[2]);local owner,oe=decode(ownerraw,"owner_node");if oe then return oe end;local targetraw=redis.call("GET",KEYS[3]);local target,te=decode(targetraw,"target_node");if te then return te end
if p["GrainKey"]~=ARGV[8] then return "placement_not_found" end;if p["PlacementID"]~=ARGV[15] or tostring(p["Version"])~=ARGV[6] then return "version_conflict" end;if p["Status"]~="active" then if ARGV[1]=="recover" then return "not_recoverable" end;return "placement_not_found" end
local seq,se=read_counter(KEYS[10],"sequence","9007199254740991");if se then return se end;local now=now_millis()
if ARGV[1]=="release" then if p["NodeIdentity"]~=ARGV[3] then return "invalid_owner" end;if not owner or owner["NodeKey"]~=KEYS[2] or owner["NodeIdentity"]~=p["NodeIdentity"] or owner["NodeType"]~=ARGV[9] or owner["NodeGroup"]~=ARGV[10] or owner["NodeName"]~=ARGV[11] then return "owner_unavailable" end;if p["OwnerNodeSessionID"]~=ARGV[5] or owner["NodeSessionID"]~=ARGV[5] then return "invalid_node_session" end
else
 if ARGV[1]=="transfer" and ARGV[3]~="" and p["NodeIdentity"]~=ARGV[3] then return "invalid_owner" end
 if ARGV[1]=="recover" then local owner_score=owner and redis.call("ZSCORE",KEYS[8],KEYS[2]) or nil;local healthy=owner and owner["NodeKey"]==KEYS[2] and owner["NodeIdentity"]==p["NodeIdentity"] and owner["NodeSessionID"]==p["OwnerNodeSessionID"] and (owner["Status"]=="active" or owner["Status"]=="draining") and owner_score and tonumber(owner_score)==tonumber(owner["Lease"]["ExpireAtUnixMilli"] or -1) and tonumber(owner_score)>now;if healthy then return "not_recoverable" end end
 if not target or target["NodeKey"]~=KEYS[3] or target["NodeIdentity"]~=ARGV[4] or target["NodeType"]~=ARGV[12] or target["NodeGroup"]~=ARGV[13] or target["NodeName"]~=ARGV[14] or target["PlacementNodeKey"]~=KEYS[5] or target["Status"]~="active" or redis.call("SISMEMBER",KEYS[9],target["NodeName"])~=0 then return "no_available_node" end;local score=redis.call("ZSCORE",KEYS[6],KEYS[3]);if not score or tonumber(score)~=tonumber(target["Lease"]["ExpireAtUnixMilli"] or -1) or tonumber(score)<=now then return "no_available_node" end
end
p["Version"]=tonumber(p["Version"])+1;p["UpdateTimeUnixMilli"]=now;local encoded=cjson.encode(p)
redis.call("ZREM",KEYS[4],p["GrainKey"]);if ARGV[1]=="release" then redis.call("DEL",KEYS[1]) else p["NodeIdentity"]=target["NodeIdentity"];p["OwnerNodeSessionID"]=target["NodeSessionID"];encoded=cjson.encode(p);redis.call("SET",KEYS[1],encoded);local score=redis.call("INCR",KEYS[10]);redis.call("ZADD",KEYS[5],score,p["GrainKey"]) end;event(KEYS[7],ARGV[7],p["GrainKey"],p["PlacementID"],p["NodeIdentity"],p["OwnerNodeSessionID"],tostring(p["Version"]),"0");return encoded

